[package]
name = "starknet_hello_world"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.4"

[dev-dependencies]
assert_macros = "2.11.4"

[[target.starknet-contract]]

[tool.voyager]
balance ={path= "lib.cairo"}