[package]
name = "cairo_2_4_4"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.2.0"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
 
# Enable CASM codegen.
casm = false
# Emit Python-powered hints in order to run compiled CASM class with legacy Cairo VM.
casm-add-pythonic-hints = false
 
# Enable allowed libfuncs validation.
allowed-libfuncs = true
# Raise errors instead of warnings if disallowed libfuncs are found.
allowed-libfuncs-deny = false

[tool.voyager]
ERC20 ={path= "erc_20.cairo", address = ""}